### ISSUE TITLE
Adapting simulation study code for other distances

### ISSUE THREAD

**Issue by ms609** [afmagee/treess#1]
Hi Andrew,

Thanks for providing this fantastic package.  I've been looking into how the ESS behaves when using my `TreeDist::ClusteringInfoDistance()` distance measure – I'd like to explore whether it can produce better ESS estimates, and if it can, whether this is worth the additional computational cost.

It's been dead easy to get `treess()` working with this distance, and thanks to your excellent code and documentation I've been able to easily replicate your real data example (Scantlebury, Fig. 6 in https://doi.org/10.1214/22-BA1339) with the adjusted distances – which is showing that the CID does produce subtly different ESS estimates.

![image](https://github.com/user-attachments/assets/49f2b554-04a7-43c5-935d-328500f426ec)

What I'd really like to do is to repeat the simulation studies, to get a better handle on these values are closer to the "correct" CID estimates.   But I can't quite work out how to do this using the `simulation_study` scripts; I can't locate the script that actually calculates the ESS values.  Would you be able to point me in the right direction?

Thanks,

Martin

**Comment by afmagee** [comment]
Hi Martin,

Good question. I had to go back and check a few things to see how things worked (and why they work that way).

The ESS computation is broken into two steps in `effectiveSizeEquivalentError`. First [it computes the distance matrix](https://github.com/afmagee/treess/blob/0a515b8ea9326deaa1a739dfd5d346e04763c41f/R/effectiveSizeEquivalentError.R#L51) for all trees in the set that the "fake" MCMC targets, then from that it constructs the [distance matrix for each chain](https://github.com/afmagee/treess/blob/0a515b8ea9326deaa1a739dfd5d346e04763c41f/R/effectiveSizeEquivalentError.R#L69) on the fly and feeds that to the internal ESS functions (which all operate directly on distance matrices). At the cost of some opacity, this structure cuts down on re-computation of tree-to-tree distances (once per set of chains, rather than once per chain).

However, looking back at this I see now this is one of the few parts of the package that does not support multiple tree distances. I'm happy to fix this so it can work more like `treess::treess` if that would be helpful.

Regardless, I'm gratified to see this package getting some use, and curious to see what comes of it!

Best,
Andy

**Comment by ms609** [comment]
Ah, that makes sense – and certainly the cost of calculating the same distances multiple times is worth avoiding.  If it's easy to support a `distance` parameter as `treess` does, that'd be fantastic – thank you!

**Comment by afmagee** [comment]
You should be good to go, arbitrary distance functions are now allowed, e.g.
```
post <- simulatePhylogeneticMCMC(constructAdjacencyGraph(phangorn::allTrees(5)),ngen=50,nchains=4)
effectiveSizeEquivalentError(post, phangorn::path.dist)
```

**Comment by ms609** [comment]
That's super, thanks so much!  I've downloaded it and it's running smoothly.
